# Generated by Django 5.1.2 on 2024-12-06 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survivors', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tradeitemrequested',
            name='trade',
        ),
        migrations.RemoveField(
            model_name='tradeitemrequester',
            name='trade',
        ),
        migrations.RemoveField(
            model_name='tradeitemrequested',
            name='item',
        ),
        migrations.RemoveField(
            model_name='tradeitemrequester',
            name='item',
        ),
        migrations.DeleteModel(
            name='Trade',
        ),
        migrations.DeleteModel(
            name='TradeItemRequested',
        ),
        migrations.DeleteModel(
            name='TradeItemRequester',
        ),
    ]
