# Generated by Django 3.2 on 2022-01-08 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StockItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=15, verbose_name='Item')),
                ('value', models.IntegerField(verbose_name='Valor do Item')),
            ],
            options={
                'verbose_name': 'Item de Estoque',
                'verbose_name_plural': 'Itens de Estoque',
            },
        ),
    ]
