# Generated by Django 3.2 on 2022-01-08 15:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('survivors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sobreviventes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(verbose_name='Idade')),
                ('gender', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=50, verbose_name='Sexo')),
                ('lat', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Latitude')),
                ('log', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Logetude')),
                ('Status', models.BooleanField(default=False, verbose_name='Infequitado')),
                ('onwer', models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Sobrevivente')),
            ],
        ),
    ]
