# Generated by Django 3.2 on 2022-01-08 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survivors', '0002_sobreviventes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sobreviventes',
            options={'verbose_name': 'Sobrevivente', 'verbose_name_plural': 'Sobreviventes'},
        ),
    ]
