# Generated by Django 3.2 on 2022-01-08 15:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('survivors', '0003_alter_sobreviventes_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sobreviventes',
            name='onwer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Sobrevivente'),
        ),
        migrations.CreateModel(
            name='accusations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numbercomplaints', models.IntegerField(verbose_name='Número de Denúncias')),
                ('survivors', models.ManyToManyField(to='survivors.Sobreviventes', verbose_name='Sobrevivente')),
            ],
        ),
    ]
