# Generated by Django 3.2 on 2022-01-08 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survivors', '0004_auto_20220108_1214'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accusations',
            options={'verbose_name': 'Denúncia', 'verbose_name_plural': 'Denúncias'},
        ),
    ]
