# Generated by Django 3.2 on 2022-01-08 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survivors', '0005_alter_accusations_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name='Quantidade')),
                ('item', models.ManyToManyField(to='survivors.StockItems', verbose_name='Item')),
                ('survivors', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survivors.sobreviventes', verbose_name='Sobreviventes')),
            ],
            options={
                'verbose_name': 'inventário',
                'verbose_name_plural': 'inventários',
            },
        ),
    ]
